// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/auth/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/auth/service.go -destination=internal/core/auth/mocks/mock_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/ajbeattie/octobud/backend/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthService is a mock of AuthService interface.
type MockAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceMockRecorder
	isgomock struct{}
}

// MockAuthServiceMockRecorder is the mock recorder for MockAuthService.
type MockAuthServiceMockRecorder struct {
	mock *MockAuthService
}

// NewMockAuthService creates a new mock instance.
func NewMockAuthService(ctrl *gomock.Controller) *MockAuthService {
	mock := &MockAuthService{ctrl: ctrl}
	mock.recorder = &MockAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthService) EXPECT() *MockAuthServiceMockRecorder {
	return m.recorder
}

// GetUser mocks base method.
func (m *MockAuthService) GetUser(ctx context.Context) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockAuthServiceMockRecorder) GetUser(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockAuthService)(nil).GetUser), ctx)
}

// InitializeDefaultUser mocks base method.
func (m *MockAuthService) InitializeDefaultUser(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitializeDefaultUser", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// InitializeDefaultUser indicates an expected call of InitializeDefaultUser.
func (mr *MockAuthServiceMockRecorder) InitializeDefaultUser(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitializeDefaultUser", reflect.TypeOf((*MockAuthService)(nil).InitializeDefaultUser), ctx)
}

// UpdateCredentials mocks base method.
func (m *MockAuthService) UpdateCredentials(ctx context.Context, newUsername, newPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCredentials", ctx, newUsername, newPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCredentials indicates an expected call of UpdateCredentials.
func (mr *MockAuthServiceMockRecorder) UpdateCredentials(ctx, newUsername, newPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCredentials", reflect.TypeOf((*MockAuthService)(nil).UpdateCredentials), ctx, newUsername, newPassword)
}

// UpdatePassword mocks base method.
func (m *MockAuthService) UpdatePassword(ctx context.Context, newPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", ctx, newPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockAuthServiceMockRecorder) UpdatePassword(ctx, newPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockAuthService)(nil).UpdatePassword), ctx, newPassword)
}

// UpdateUsername mocks base method.
func (m *MockAuthService) UpdateUsername(ctx context.Context, newUsername string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUsername", ctx, newUsername)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUsername indicates an expected call of UpdateUsername.
func (mr *MockAuthServiceMockRecorder) UpdateUsername(ctx, newUsername any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUsername", reflect.TypeOf((*MockAuthService)(nil).UpdateUsername), ctx, newUsername)
}

// ValidatePassword mocks base method.
func (m *MockAuthService) ValidatePassword(ctx context.Context, username, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidatePassword", ctx, username, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidatePassword indicates an expected call of ValidatePassword.
func (mr *MockAuthServiceMockRecorder) ValidatePassword(ctx, username, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidatePassword", reflect.TypeOf((*MockAuthService)(nil).ValidatePassword), ctx, username, password)
}
