FROM golang:1.24 AS builder

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /bin/goose-migrations ./cmd/goose-migrations

FROM gcr.io/distroless/base-debian12

WORKDIR /app

COPY --from=builder /bin/goose-migrations /usr/local/bin/goose-migrations
COPY migrations ./migrations

ENV DATABASE_URL=""

ENTRYPOINT ["/usr/local/bin/goose-migrations"]
CMD ["up"]

