// Code generated by MockGen. DO NOT EDIT.
// Source: internal/github/client.go
//
// Generated by this command:
//
//	mockgen -destination=internal/github/mock_client_test.go -package=github -source=internal/github/client.go Client
//

// Package github is a generated GoMock package.
package github
