// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/rules/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/rules/service.go -destination=internal/core/rules/mocks/mock_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	db "github.com/ajbeattie/octobud/backend/internal/db"
	models "github.com/ajbeattie/octobud/backend/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockRuleService is a mock of RuleService interface.
type MockRuleService struct {
	ctrl     *gomock.Controller
	recorder *MockRuleServiceMockRecorder
	isgomock struct{}
}

// MockRuleServiceMockRecorder is the mock recorder for MockRuleService.
type MockRuleServiceMockRecorder struct {
	mock *MockRuleService
}

// NewMockRuleService creates a new mock instance.
func NewMockRuleService(ctrl *gomock.Controller) *MockRuleService {
	mock := &MockRuleService{ctrl: ctrl}
	mock.recorder = &MockRuleServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuleService) EXPECT() *MockRuleServiceMockRecorder {
	return m.recorder
}

// CreateRule mocks base method.
func (m *MockRuleService) CreateRule(ctx context.Context, params models.CreateRuleParams) (models.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRule", ctx, params)
	ret0, _ := ret[0].(models.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRule indicates an expected call of CreateRule.
func (mr *MockRuleServiceMockRecorder) CreateRule(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRule", reflect.TypeOf((*MockRuleService)(nil).CreateRule), ctx, params)
}

// DeleteRule mocks base method.
func (m *MockRuleService) DeleteRule(ctx context.Context, ruleID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRule", ctx, ruleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRule indicates an expected call of DeleteRule.
func (mr *MockRuleServiceMockRecorder) DeleteRule(ctx, ruleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRule", reflect.TypeOf((*MockRuleService)(nil).DeleteRule), ctx, ruleID)
}

// GetRule mocks base method.
func (m *MockRuleService) GetRule(ctx context.Context, ruleID int64) (models.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRule", ctx, ruleID)
	ret0, _ := ret[0].(models.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRule indicates an expected call of GetRule.
func (mr *MockRuleServiceMockRecorder) GetRule(ctx, ruleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRule", reflect.TypeOf((*MockRuleService)(nil).GetRule), ctx, ruleID)
}

// GetRulesByViewID mocks base method.
func (m *MockRuleService) GetRulesByViewID(ctx context.Context, viewID int64) ([]db.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRulesByViewID", ctx, viewID)
	ret0, _ := ret[0].([]db.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRulesByViewID indicates an expected call of GetRulesByViewID.
func (mr *MockRuleServiceMockRecorder) GetRulesByViewID(ctx, viewID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRulesByViewID", reflect.TypeOf((*MockRuleService)(nil).GetRulesByViewID), ctx, viewID)
}

// ListRules mocks base method.
func (m *MockRuleService) ListRules(ctx context.Context) ([]models.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRules", ctx)
	ret0, _ := ret[0].([]models.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRules indicates an expected call of ListRules.
func (mr *MockRuleServiceMockRecorder) ListRules(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRules", reflect.TypeOf((*MockRuleService)(nil).ListRules), ctx)
}

// ReorderRules mocks base method.
func (m *MockRuleService) ReorderRules(ctx context.Context, ruleIDs []int64) ([]models.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReorderRules", ctx, ruleIDs)
	ret0, _ := ret[0].([]models.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReorderRules indicates an expected call of ReorderRules.
func (mr *MockRuleServiceMockRecorder) ReorderRules(ctx, ruleIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReorderRules", reflect.TypeOf((*MockRuleService)(nil).ReorderRules), ctx, ruleIDs)
}

// UpdateRule mocks base method.
func (m *MockRuleService) UpdateRule(ctx context.Context, ruleID int64, params models.UpdateRuleParams) (models.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRule", ctx, ruleID, params)
	ret0, _ := ret[0].(models.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRule indicates an expected call of UpdateRule.
func (mr *MockRuleServiceMockRecorder) UpdateRule(ctx, ruleID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRule", reflect.TypeOf((*MockRuleService)(nil).UpdateRule), ctx, ruleID, params)
}
