// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ajbeattie/octobud/backend/internal/sync (interfaces: SyncOperations)
//
// Generated by this command:
//
//	mockgen -destination=internal/sync/mocks/mock_sync.go -package=syncmocks github.com/ajbeattie/octobud/backend/internal/sync SyncOperations
//

// Package syncmocks is a generated GoMock package.
package syncmocks

import (
	context "context"
	reflect "reflect"
	time "time"

	types "github.com/ajbeattie/octobud/backend/internal/github/types"
	sync "github.com/ajbeattie/octobud/backend/internal/sync"
	gomock "go.uber.org/mock/gomock"
)

// MockSyncOperations is a mock of SyncOperations interface.
type MockSyncOperations struct {
	ctrl     *gomock.Controller
	recorder *MockSyncOperationsMockRecorder
	isgomock struct{}
}

// MockSyncOperationsMockRecorder is the mock recorder for MockSyncOperations.
type MockSyncOperationsMockRecorder struct {
	mock *MockSyncOperations
}

// NewMockSyncOperations creates a new mock instance.
func NewMockSyncOperations(ctrl *gomock.Controller) *MockSyncOperations {
	mock := &MockSyncOperations{ctrl: ctrl}
	mock.recorder = &MockSyncOperationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyncOperations) EXPECT() *MockSyncOperationsMockRecorder {
	return m.recorder
}

// FetchNotificationsToSync mocks base method.
func (m *MockSyncOperations) FetchNotificationsToSync(ctx context.Context, syncCtx sync.SyncContext) ([]types.NotificationThread, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchNotificationsToSync", ctx, syncCtx)
	ret0, _ := ret[0].([]types.NotificationThread)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchNotificationsToSync indicates an expected call of FetchNotificationsToSync.
func (mr *MockSyncOperationsMockRecorder) FetchNotificationsToSync(ctx, syncCtx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchNotificationsToSync", reflect.TypeOf((*MockSyncOperations)(nil).FetchNotificationsToSync), ctx, syncCtx)
}

// GetSyncContext mocks base method.
func (m *MockSyncOperations) GetSyncContext(ctx context.Context) (sync.SyncContext, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSyncContext", ctx)
	ret0, _ := ret[0].(sync.SyncContext)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSyncContext indicates an expected call of GetSyncContext.
func (mr *MockSyncOperationsMockRecorder) GetSyncContext(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSyncContext", reflect.TypeOf((*MockSyncOperations)(nil).GetSyncContext), ctx)
}

// ProcessNotification mocks base method.
func (m *MockSyncOperations) ProcessNotification(ctx context.Context, thread types.NotificationThread) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessNotification", ctx, thread)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessNotification indicates an expected call of ProcessNotification.
func (mr *MockSyncOperationsMockRecorder) ProcessNotification(ctx, thread any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessNotification", reflect.TypeOf((*MockSyncOperations)(nil).ProcessNotification), ctx, thread)
}

// UpdateSyncStateAfterProcessing mocks base method.
func (m *MockSyncOperations) UpdateSyncStateAfterProcessing(ctx context.Context, latestUpdate time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSyncStateAfterProcessing", ctx, latestUpdate)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSyncStateAfterProcessing indicates an expected call of UpdateSyncStateAfterProcessing.
func (mr *MockSyncOperationsMockRecorder) UpdateSyncStateAfterProcessing(ctx, latestUpdate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSyncStateAfterProcessing", reflect.TypeOf((*MockSyncOperations)(nil).UpdateSyncStateAfterProcessing), ctx, latestUpdate)
}

// UpdateSyncStateAfterProcessingWithInitialSync mocks base method.
func (m *MockSyncOperations) UpdateSyncStateAfterProcessingWithInitialSync(ctx context.Context, latestUpdate time.Time, initialSyncCompletedAt, oldestNotificationSyncedAt *time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSyncStateAfterProcessingWithInitialSync", ctx, latestUpdate, initialSyncCompletedAt, oldestNotificationSyncedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSyncStateAfterProcessingWithInitialSync indicates an expected call of UpdateSyncStateAfterProcessingWithInitialSync.
func (mr *MockSyncOperationsMockRecorder) UpdateSyncStateAfterProcessingWithInitialSync(ctx, latestUpdate, initialSyncCompletedAt, oldestNotificationSyncedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSyncStateAfterProcessingWithInitialSync", reflect.TypeOf((*MockSyncOperations)(nil).UpdateSyncStateAfterProcessingWithInitialSync), ctx, latestUpdate, initialSyncCompletedAt, oldestNotificationSyncedAt)
}
