// Code generated by MockGen. DO NOT EDIT.
// Source: internal/db/store.go
//
// Generated by this command:
//
//	mockgen -source=internal/db/store.go -destination=internal/db/mocks/mock_store.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	db "github.com/ajbeattie/octobud/backend/internal/db"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// ArchiveNotification mocks base method.
func (m *MockStore) ArchiveNotification(ctx context.Context, githubID string) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ArchiveNotification", ctx, githubID)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ArchiveNotification indicates an expected call of ArchiveNotification.
func (mr *MockStoreMockRecorder) ArchiveNotification(ctx, githubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArchiveNotification", reflect.TypeOf((*MockStore)(nil).ArchiveNotification), ctx, githubID)
}

// AssignTagToEntity mocks base method.
func (m *MockStore) AssignTagToEntity(ctx context.Context, arg db.AssignTagToEntityParams) (db.TagAssignment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignTagToEntity", ctx, arg)
	ret0, _ := ret[0].(db.TagAssignment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AssignTagToEntity indicates an expected call of AssignTagToEntity.
func (mr *MockStoreMockRecorder) AssignTagToEntity(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignTagToEntity", reflect.TypeOf((*MockStore)(nil).AssignTagToEntity), ctx, arg)
}

// BulkArchiveNotifications mocks base method.
func (m *MockStore) BulkArchiveNotifications(ctx context.Context, githubIds []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkArchiveNotifications", ctx, githubIds)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkArchiveNotifications indicates an expected call of BulkArchiveNotifications.
func (mr *MockStoreMockRecorder) BulkArchiveNotifications(ctx, githubIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkArchiveNotifications", reflect.TypeOf((*MockStore)(nil).BulkArchiveNotifications), ctx, githubIds)
}

// BulkArchiveNotificationsByQuery mocks base method.
func (m *MockStore) BulkArchiveNotificationsByQuery(ctx context.Context, query db.NotificationQuery) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkArchiveNotificationsByQuery", ctx, query)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkArchiveNotificationsByQuery indicates an expected call of BulkArchiveNotificationsByQuery.
func (mr *MockStoreMockRecorder) BulkArchiveNotificationsByQuery(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkArchiveNotificationsByQuery", reflect.TypeOf((*MockStore)(nil).BulkArchiveNotificationsByQuery), ctx, query)
}

// BulkMarkNotificationsRead mocks base method.
func (m *MockStore) BulkMarkNotificationsRead(ctx context.Context, githubIds []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkMarkNotificationsRead", ctx, githubIds)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkMarkNotificationsRead indicates an expected call of BulkMarkNotificationsRead.
func (mr *MockStoreMockRecorder) BulkMarkNotificationsRead(ctx, githubIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkMarkNotificationsRead", reflect.TypeOf((*MockStore)(nil).BulkMarkNotificationsRead), ctx, githubIds)
}

// BulkMarkNotificationsReadByQuery mocks base method.
func (m *MockStore) BulkMarkNotificationsReadByQuery(ctx context.Context, query db.NotificationQuery) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkMarkNotificationsReadByQuery", ctx, query)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkMarkNotificationsReadByQuery indicates an expected call of BulkMarkNotificationsReadByQuery.
func (mr *MockStoreMockRecorder) BulkMarkNotificationsReadByQuery(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkMarkNotificationsReadByQuery", reflect.TypeOf((*MockStore)(nil).BulkMarkNotificationsReadByQuery), ctx, query)
}

// BulkMarkNotificationsUnfiltered mocks base method.
func (m *MockStore) BulkMarkNotificationsUnfiltered(ctx context.Context, githubIds []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkMarkNotificationsUnfiltered", ctx, githubIds)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkMarkNotificationsUnfiltered indicates an expected call of BulkMarkNotificationsUnfiltered.
func (mr *MockStoreMockRecorder) BulkMarkNotificationsUnfiltered(ctx, githubIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkMarkNotificationsUnfiltered", reflect.TypeOf((*MockStore)(nil).BulkMarkNotificationsUnfiltered), ctx, githubIds)
}

// BulkMarkNotificationsUnread mocks base method.
func (m *MockStore) BulkMarkNotificationsUnread(ctx context.Context, githubIds []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkMarkNotificationsUnread", ctx, githubIds)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkMarkNotificationsUnread indicates an expected call of BulkMarkNotificationsUnread.
func (mr *MockStoreMockRecorder) BulkMarkNotificationsUnread(ctx, githubIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkMarkNotificationsUnread", reflect.TypeOf((*MockStore)(nil).BulkMarkNotificationsUnread), ctx, githubIds)
}

// BulkMarkNotificationsUnreadByQuery mocks base method.
func (m *MockStore) BulkMarkNotificationsUnreadByQuery(ctx context.Context, query db.NotificationQuery) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkMarkNotificationsUnreadByQuery", ctx, query)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkMarkNotificationsUnreadByQuery indicates an expected call of BulkMarkNotificationsUnreadByQuery.
func (mr *MockStoreMockRecorder) BulkMarkNotificationsUnreadByQuery(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkMarkNotificationsUnreadByQuery", reflect.TypeOf((*MockStore)(nil).BulkMarkNotificationsUnreadByQuery), ctx, query)
}

// BulkMuteNotifications mocks base method.
func (m *MockStore) BulkMuteNotifications(ctx context.Context, githubIds []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkMuteNotifications", ctx, githubIds)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkMuteNotifications indicates an expected call of BulkMuteNotifications.
func (mr *MockStoreMockRecorder) BulkMuteNotifications(ctx, githubIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkMuteNotifications", reflect.TypeOf((*MockStore)(nil).BulkMuteNotifications), ctx, githubIds)
}

// BulkMuteNotificationsByQuery mocks base method.
func (m *MockStore) BulkMuteNotificationsByQuery(ctx context.Context, query db.NotificationQuery) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkMuteNotificationsByQuery", ctx, query)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkMuteNotificationsByQuery indicates an expected call of BulkMuteNotificationsByQuery.
func (mr *MockStoreMockRecorder) BulkMuteNotificationsByQuery(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkMuteNotificationsByQuery", reflect.TypeOf((*MockStore)(nil).BulkMuteNotificationsByQuery), ctx, query)
}

// BulkSnoozeNotifications mocks base method.
func (m *MockStore) BulkSnoozeNotifications(ctx context.Context, arg db.BulkSnoozeNotificationsParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkSnoozeNotifications", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkSnoozeNotifications indicates an expected call of BulkSnoozeNotifications.
func (mr *MockStoreMockRecorder) BulkSnoozeNotifications(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkSnoozeNotifications", reflect.TypeOf((*MockStore)(nil).BulkSnoozeNotifications), ctx, arg)
}

// BulkSnoozeNotificationsByQuery mocks base method.
func (m *MockStore) BulkSnoozeNotificationsByQuery(ctx context.Context, arg db.BulkSnoozeNotificationsByQueryParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkSnoozeNotificationsByQuery", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkSnoozeNotificationsByQuery indicates an expected call of BulkSnoozeNotificationsByQuery.
func (mr *MockStoreMockRecorder) BulkSnoozeNotificationsByQuery(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkSnoozeNotificationsByQuery", reflect.TypeOf((*MockStore)(nil).BulkSnoozeNotificationsByQuery), ctx, arg)
}

// BulkStarNotifications mocks base method.
func (m *MockStore) BulkStarNotifications(ctx context.Context, githubIds []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkStarNotifications", ctx, githubIds)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkStarNotifications indicates an expected call of BulkStarNotifications.
func (mr *MockStoreMockRecorder) BulkStarNotifications(ctx, githubIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkStarNotifications", reflect.TypeOf((*MockStore)(nil).BulkStarNotifications), ctx, githubIds)
}

// BulkStarNotificationsByQuery mocks base method.
func (m *MockStore) BulkStarNotificationsByQuery(ctx context.Context, query db.NotificationQuery) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkStarNotificationsByQuery", ctx, query)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkStarNotificationsByQuery indicates an expected call of BulkStarNotificationsByQuery.
func (mr *MockStoreMockRecorder) BulkStarNotificationsByQuery(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkStarNotificationsByQuery", reflect.TypeOf((*MockStore)(nil).BulkStarNotificationsByQuery), ctx, query)
}

// BulkUnarchiveNotifications mocks base method.
func (m *MockStore) BulkUnarchiveNotifications(ctx context.Context, githubIds []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUnarchiveNotifications", ctx, githubIds)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkUnarchiveNotifications indicates an expected call of BulkUnarchiveNotifications.
func (mr *MockStoreMockRecorder) BulkUnarchiveNotifications(ctx, githubIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUnarchiveNotifications", reflect.TypeOf((*MockStore)(nil).BulkUnarchiveNotifications), ctx, githubIds)
}

// BulkUnarchiveNotificationsByQuery mocks base method.
func (m *MockStore) BulkUnarchiveNotificationsByQuery(ctx context.Context, query db.NotificationQuery) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUnarchiveNotificationsByQuery", ctx, query)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkUnarchiveNotificationsByQuery indicates an expected call of BulkUnarchiveNotificationsByQuery.
func (mr *MockStoreMockRecorder) BulkUnarchiveNotificationsByQuery(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUnarchiveNotificationsByQuery", reflect.TypeOf((*MockStore)(nil).BulkUnarchiveNotificationsByQuery), ctx, query)
}

// BulkUnmuteNotifications mocks base method.
func (m *MockStore) BulkUnmuteNotifications(ctx context.Context, githubIds []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUnmuteNotifications", ctx, githubIds)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkUnmuteNotifications indicates an expected call of BulkUnmuteNotifications.
func (mr *MockStoreMockRecorder) BulkUnmuteNotifications(ctx, githubIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUnmuteNotifications", reflect.TypeOf((*MockStore)(nil).BulkUnmuteNotifications), ctx, githubIds)
}

// BulkUnmuteNotificationsByQuery mocks base method.
func (m *MockStore) BulkUnmuteNotificationsByQuery(ctx context.Context, query db.NotificationQuery) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUnmuteNotificationsByQuery", ctx, query)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkUnmuteNotificationsByQuery indicates an expected call of BulkUnmuteNotificationsByQuery.
func (mr *MockStoreMockRecorder) BulkUnmuteNotificationsByQuery(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUnmuteNotificationsByQuery", reflect.TypeOf((*MockStore)(nil).BulkUnmuteNotificationsByQuery), ctx, query)
}

// BulkUnsnoozeNotifications mocks base method.
func (m *MockStore) BulkUnsnoozeNotifications(ctx context.Context, githubIds []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUnsnoozeNotifications", ctx, githubIds)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkUnsnoozeNotifications indicates an expected call of BulkUnsnoozeNotifications.
func (mr *MockStoreMockRecorder) BulkUnsnoozeNotifications(ctx, githubIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUnsnoozeNotifications", reflect.TypeOf((*MockStore)(nil).BulkUnsnoozeNotifications), ctx, githubIds)
}

// BulkUnsnoozeNotificationsByQuery mocks base method.
func (m *MockStore) BulkUnsnoozeNotificationsByQuery(ctx context.Context, query db.NotificationQuery) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUnsnoozeNotificationsByQuery", ctx, query)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkUnsnoozeNotificationsByQuery indicates an expected call of BulkUnsnoozeNotificationsByQuery.
func (mr *MockStoreMockRecorder) BulkUnsnoozeNotificationsByQuery(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUnsnoozeNotificationsByQuery", reflect.TypeOf((*MockStore)(nil).BulkUnsnoozeNotificationsByQuery), ctx, query)
}

// BulkUnstarNotifications mocks base method.
func (m *MockStore) BulkUnstarNotifications(ctx context.Context, githubIds []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUnstarNotifications", ctx, githubIds)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkUnstarNotifications indicates an expected call of BulkUnstarNotifications.
func (mr *MockStoreMockRecorder) BulkUnstarNotifications(ctx, githubIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUnstarNotifications", reflect.TypeOf((*MockStore)(nil).BulkUnstarNotifications), ctx, githubIds)
}

// BulkUnstarNotificationsByQuery mocks base method.
func (m *MockStore) BulkUnstarNotificationsByQuery(ctx context.Context, query db.NotificationQuery) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUnstarNotificationsByQuery", ctx, query)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkUnstarNotificationsByQuery indicates an expected call of BulkUnstarNotificationsByQuery.
func (mr *MockStoreMockRecorder) BulkUnstarNotificationsByQuery(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUnstarNotificationsByQuery", reflect.TypeOf((*MockStore)(nil).BulkUnstarNotificationsByQuery), ctx, query)
}

// CreateRule mocks base method.
func (m *MockStore) CreateRule(ctx context.Context, arg db.CreateRuleParams) (db.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRule", ctx, arg)
	ret0, _ := ret[0].(db.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRule indicates an expected call of CreateRule.
func (mr *MockStoreMockRecorder) CreateRule(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRule", reflect.TypeOf((*MockStore)(nil).CreateRule), ctx, arg)
}

// CreateUser mocks base method.
func (m *MockStore) CreateUser(ctx context.Context, arg db.CreateUserParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, arg)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockStoreMockRecorder) CreateUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockStore)(nil).CreateUser), ctx, arg)
}

// CreateView mocks base method.
func (m *MockStore) CreateView(ctx context.Context, arg db.CreateViewParams) (db.View, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateView", ctx, arg)
	ret0, _ := ret[0].(db.View)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateView indicates an expected call of CreateView.
func (mr *MockStoreMockRecorder) CreateView(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateView", reflect.TypeOf((*MockStore)(nil).CreateView), ctx, arg)
}

// DeleteRule mocks base method.
func (m *MockStore) DeleteRule(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRule", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRule indicates an expected call of DeleteRule.
func (mr *MockStoreMockRecorder) DeleteRule(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRule", reflect.TypeOf((*MockStore)(nil).DeleteRule), ctx, id)
}

// DeleteTag mocks base method.
func (m *MockStore) DeleteTag(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTag", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTag indicates an expected call of DeleteTag.
func (mr *MockStoreMockRecorder) DeleteTag(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTag", reflect.TypeOf((*MockStore)(nil).DeleteTag), ctx, id)
}

// DeleteView mocks base method.
func (m *MockStore) DeleteView(ctx context.Context, id int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteView", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteView indicates an expected call of DeleteView.
func (mr *MockStoreMockRecorder) DeleteView(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteView", reflect.TypeOf((*MockStore)(nil).DeleteView), ctx, id)
}

// GetNotificationByGithubID mocks base method.
func (m *MockStore) GetNotificationByGithubID(ctx context.Context, githubID string) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotificationByGithubID", ctx, githubID)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotificationByGithubID indicates an expected call of GetNotificationByGithubID.
func (mr *MockStoreMockRecorder) GetNotificationByGithubID(ctx, githubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotificationByGithubID", reflect.TypeOf((*MockStore)(nil).GetNotificationByGithubID), ctx, githubID)
}

// GetNotificationByID mocks base method.
func (m *MockStore) GetNotificationByID(ctx context.Context, id int64) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotificationByID", ctx, id)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotificationByID indicates an expected call of GetNotificationByID.
func (mr *MockStoreMockRecorder) GetNotificationByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotificationByID", reflect.TypeOf((*MockStore)(nil).GetNotificationByID), ctx, id)
}

// GetRepositoryByID mocks base method.
func (m *MockStore) GetRepositoryByID(ctx context.Context, id int64) (db.Repository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepositoryByID", ctx, id)
	ret0, _ := ret[0].(db.Repository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepositoryByID indicates an expected call of GetRepositoryByID.
func (mr *MockStoreMockRecorder) GetRepositoryByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepositoryByID", reflect.TypeOf((*MockStore)(nil).GetRepositoryByID), ctx, id)
}

// GetRule mocks base method.
func (m *MockStore) GetRule(ctx context.Context, id int64) (db.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRule", ctx, id)
	ret0, _ := ret[0].(db.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRule indicates an expected call of GetRule.
func (mr *MockStoreMockRecorder) GetRule(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRule", reflect.TypeOf((*MockStore)(nil).GetRule), ctx, id)
}

// GetRulesByViewID mocks base method.
func (m *MockStore) GetRulesByViewID(ctx context.Context, viewID sql.NullInt64) ([]db.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRulesByViewID", ctx, viewID)
	ret0, _ := ret[0].([]db.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRulesByViewID indicates an expected call of GetRulesByViewID.
func (mr *MockStoreMockRecorder) GetRulesByViewID(ctx, viewID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRulesByViewID", reflect.TypeOf((*MockStore)(nil).GetRulesByViewID), ctx, viewID)
}

// GetSyncState mocks base method.
func (m *MockStore) GetSyncState(ctx context.Context) (db.GetSyncStateRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSyncState", ctx)
	ret0, _ := ret[0].(db.GetSyncStateRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSyncState indicates an expected call of GetSyncState.
func (mr *MockStoreMockRecorder) GetSyncState(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSyncState", reflect.TypeOf((*MockStore)(nil).GetSyncState), ctx)
}

// GetTag mocks base method.
func (m *MockStore) GetTag(ctx context.Context, id int64) (db.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTag", ctx, id)
	ret0, _ := ret[0].(db.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTag indicates an expected call of GetTag.
func (mr *MockStoreMockRecorder) GetTag(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTag", reflect.TypeOf((*MockStore)(nil).GetTag), ctx, id)
}

// GetTagByName mocks base method.
func (m *MockStore) GetTagByName(ctx context.Context, name string) (db.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTagByName", ctx, name)
	ret0, _ := ret[0].(db.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTagByName indicates an expected call of GetTagByName.
func (mr *MockStoreMockRecorder) GetTagByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTagByName", reflect.TypeOf((*MockStore)(nil).GetTagByName), ctx, name)
}

// GetUser mocks base method.
func (m *MockStore) GetUser(ctx context.Context) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockStoreMockRecorder) GetUser(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockStore)(nil).GetUser), ctx)
}

// GetView mocks base method.
func (m *MockStore) GetView(ctx context.Context, id int64) (db.View, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetView", ctx, id)
	ret0, _ := ret[0].(db.View)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetView indicates an expected call of GetView.
func (mr *MockStoreMockRecorder) GetView(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetView", reflect.TypeOf((*MockStore)(nil).GetView), ctx, id)
}

// ListAllTags mocks base method.
func (m *MockStore) ListAllTags(ctx context.Context) ([]db.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllTags", ctx)
	ret0, _ := ret[0].([]db.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllTags indicates an expected call of ListAllTags.
func (mr *MockStoreMockRecorder) ListAllTags(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllTags", reflect.TypeOf((*MockStore)(nil).ListAllTags), ctx)
}

// ListEnabledRulesOrdered mocks base method.
func (m *MockStore) ListEnabledRulesOrdered(ctx context.Context) ([]db.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEnabledRulesOrdered", ctx)
	ret0, _ := ret[0].([]db.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEnabledRulesOrdered indicates an expected call of ListEnabledRulesOrdered.
func (mr *MockStoreMockRecorder) ListEnabledRulesOrdered(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEnabledRulesOrdered", reflect.TypeOf((*MockStore)(nil).ListEnabledRulesOrdered), ctx)
}

// ListNotificationsFromQuery mocks base method.
func (m *MockStore) ListNotificationsFromQuery(ctx context.Context, query db.NotificationQuery) (db.ListNotificationsFromQueryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNotificationsFromQuery", ctx, query)
	ret0, _ := ret[0].(db.ListNotificationsFromQueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNotificationsFromQuery indicates an expected call of ListNotificationsFromQuery.
func (mr *MockStoreMockRecorder) ListNotificationsFromQuery(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNotificationsFromQuery", reflect.TypeOf((*MockStore)(nil).ListNotificationsFromQuery), ctx, query)
}

// ListRepositories mocks base method.
func (m *MockStore) ListRepositories(ctx context.Context) ([]db.Repository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRepositories", ctx)
	ret0, _ := ret[0].([]db.Repository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRepositories indicates an expected call of ListRepositories.
func (mr *MockStoreMockRecorder) ListRepositories(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRepositories", reflect.TypeOf((*MockStore)(nil).ListRepositories), ctx)
}

// ListRules mocks base method.
func (m *MockStore) ListRules(ctx context.Context) ([]db.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRules", ctx)
	ret0, _ := ret[0].([]db.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRules indicates an expected call of ListRules.
func (mr *MockStoreMockRecorder) ListRules(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRules", reflect.TypeOf((*MockStore)(nil).ListRules), ctx)
}

// ListTagsForEntity mocks base method.
func (m *MockStore) ListTagsForEntity(ctx context.Context, arg db.ListTagsForEntityParams) ([]db.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTagsForEntity", ctx, arg)
	ret0, _ := ret[0].([]db.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTagsForEntity indicates an expected call of ListTagsForEntity.
func (mr *MockStoreMockRecorder) ListTagsForEntity(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTagsForEntity", reflect.TypeOf((*MockStore)(nil).ListTagsForEntity), ctx, arg)
}

// ListViews mocks base method.
func (m *MockStore) ListViews(ctx context.Context) ([]db.View, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListViews", ctx)
	ret0, _ := ret[0].([]db.View)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListViews indicates an expected call of ListViews.
func (mr *MockStoreMockRecorder) ListViews(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListViews", reflect.TypeOf((*MockStore)(nil).ListViews), ctx)
}

// MarkNotificationFiltered mocks base method.
func (m *MockStore) MarkNotificationFiltered(ctx context.Context, githubID string) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkNotificationFiltered", ctx, githubID)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkNotificationFiltered indicates an expected call of MarkNotificationFiltered.
func (mr *MockStoreMockRecorder) MarkNotificationFiltered(ctx, githubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkNotificationFiltered", reflect.TypeOf((*MockStore)(nil).MarkNotificationFiltered), ctx, githubID)
}

// MarkNotificationRead mocks base method.
func (m *MockStore) MarkNotificationRead(ctx context.Context, githubID string) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkNotificationRead", ctx, githubID)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkNotificationRead indicates an expected call of MarkNotificationRead.
func (mr *MockStoreMockRecorder) MarkNotificationRead(ctx, githubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkNotificationRead", reflect.TypeOf((*MockStore)(nil).MarkNotificationRead), ctx, githubID)
}

// MarkNotificationUnfiltered mocks base method.
func (m *MockStore) MarkNotificationUnfiltered(ctx context.Context, githubID string) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkNotificationUnfiltered", ctx, githubID)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkNotificationUnfiltered indicates an expected call of MarkNotificationUnfiltered.
func (mr *MockStoreMockRecorder) MarkNotificationUnfiltered(ctx, githubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkNotificationUnfiltered", reflect.TypeOf((*MockStore)(nil).MarkNotificationUnfiltered), ctx, githubID)
}

// MarkNotificationUnread mocks base method.
func (m *MockStore) MarkNotificationUnread(ctx context.Context, githubID string) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkNotificationUnread", ctx, githubID)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkNotificationUnread indicates an expected call of MarkNotificationUnread.
func (mr *MockStoreMockRecorder) MarkNotificationUnread(ctx, githubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkNotificationUnread", reflect.TypeOf((*MockStore)(nil).MarkNotificationUnread), ctx, githubID)
}

// MuteNotification mocks base method.
func (m *MockStore) MuteNotification(ctx context.Context, githubID string) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MuteNotification", ctx, githubID)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MuteNotification indicates an expected call of MuteNotification.
func (mr *MockStoreMockRecorder) MuteNotification(ctx, githubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MuteNotification", reflect.TypeOf((*MockStore)(nil).MuteNotification), ctx, githubID)
}

// RemoveTagAssignment mocks base method.
func (m *MockStore) RemoveTagAssignment(ctx context.Context, arg db.RemoveTagAssignmentParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveTagAssignment", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveTagAssignment indicates an expected call of RemoveTagAssignment.
func (mr *MockStoreMockRecorder) RemoveTagAssignment(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveTagAssignment", reflect.TypeOf((*MockStore)(nil).RemoveTagAssignment), ctx, arg)
}

// SnoozeNotification mocks base method.
func (m *MockStore) SnoozeNotification(ctx context.Context, arg db.SnoozeNotificationParams) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SnoozeNotification", ctx, arg)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SnoozeNotification indicates an expected call of SnoozeNotification.
func (mr *MockStoreMockRecorder) SnoozeNotification(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SnoozeNotification", reflect.TypeOf((*MockStore)(nil).SnoozeNotification), ctx, arg)
}

// StarNotification mocks base method.
func (m *MockStore) StarNotification(ctx context.Context, githubID string) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StarNotification", ctx, githubID)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StarNotification indicates an expected call of StarNotification.
func (mr *MockStoreMockRecorder) StarNotification(ctx, githubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StarNotification", reflect.TypeOf((*MockStore)(nil).StarNotification), ctx, githubID)
}

// UnarchiveNotification mocks base method.
func (m *MockStore) UnarchiveNotification(ctx context.Context, githubID string) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnarchiveNotification", ctx, githubID)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnarchiveNotification indicates an expected call of UnarchiveNotification.
func (mr *MockStoreMockRecorder) UnarchiveNotification(ctx, githubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnarchiveNotification", reflect.TypeOf((*MockStore)(nil).UnarchiveNotification), ctx, githubID)
}

// UnmuteNotification mocks base method.
func (m *MockStore) UnmuteNotification(ctx context.Context, githubID string) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnmuteNotification", ctx, githubID)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnmuteNotification indicates an expected call of UnmuteNotification.
func (mr *MockStoreMockRecorder) UnmuteNotification(ctx, githubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmuteNotification", reflect.TypeOf((*MockStore)(nil).UnmuteNotification), ctx, githubID)
}

// UnsnoozeNotification mocks base method.
func (m *MockStore) UnsnoozeNotification(ctx context.Context, githubID string) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnsnoozeNotification", ctx, githubID)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnsnoozeNotification indicates an expected call of UnsnoozeNotification.
func (mr *MockStoreMockRecorder) UnsnoozeNotification(ctx, githubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnsnoozeNotification", reflect.TypeOf((*MockStore)(nil).UnsnoozeNotification), ctx, githubID)
}

// UnstarNotification mocks base method.
func (m *MockStore) UnstarNotification(ctx context.Context, githubID string) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnstarNotification", ctx, githubID)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnstarNotification indicates an expected call of UnstarNotification.
func (mr *MockStoreMockRecorder) UnstarNotification(ctx, githubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnstarNotification", reflect.TypeOf((*MockStore)(nil).UnstarNotification), ctx, githubID)
}

// UpdateNotificationSubject mocks base method.
func (m *MockStore) UpdateNotificationSubject(ctx context.Context, arg db.UpdateNotificationSubjectParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNotificationSubject", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateNotificationSubject indicates an expected call of UpdateNotificationSubject.
func (mr *MockStoreMockRecorder) UpdateNotificationSubject(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNotificationSubject", reflect.TypeOf((*MockStore)(nil).UpdateNotificationSubject), ctx, arg)
}

// UpdateNotificationTagIds mocks base method.
func (m *MockStore) UpdateNotificationTagIds(ctx context.Context, notificationID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNotificationTagIds", ctx, notificationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateNotificationTagIds indicates an expected call of UpdateNotificationTagIds.
func (mr *MockStoreMockRecorder) UpdateNotificationTagIds(ctx, notificationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNotificationTagIds", reflect.TypeOf((*MockStore)(nil).UpdateNotificationTagIds), ctx, notificationID)
}

// UpdateRule mocks base method.
func (m *MockStore) UpdateRule(ctx context.Context, arg db.UpdateRuleParams) (db.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRule", ctx, arg)
	ret0, _ := ret[0].(db.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRule indicates an expected call of UpdateRule.
func (mr *MockStoreMockRecorder) UpdateRule(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRule", reflect.TypeOf((*MockStore)(nil).UpdateRule), ctx, arg)
}

// UpdateRuleOrder mocks base method.
func (m *MockStore) UpdateRuleOrder(ctx context.Context, arg db.UpdateRuleOrderParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRuleOrder", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRuleOrder indicates an expected call of UpdateRuleOrder.
func (mr *MockStoreMockRecorder) UpdateRuleOrder(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRuleOrder", reflect.TypeOf((*MockStore)(nil).UpdateRuleOrder), ctx, arg)
}

// UpdateTag mocks base method.
func (m *MockStore) UpdateTag(ctx context.Context, arg db.UpdateTagParams) (db.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTag", ctx, arg)
	ret0, _ := ret[0].(db.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTag indicates an expected call of UpdateTag.
func (mr *MockStoreMockRecorder) UpdateTag(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTag", reflect.TypeOf((*MockStore)(nil).UpdateTag), ctx, arg)
}

// UpdateTagDisplayOrder mocks base method.
func (m *MockStore) UpdateTagDisplayOrder(ctx context.Context, arg db.UpdateTagDisplayOrderParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTagDisplayOrder", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTagDisplayOrder indicates an expected call of UpdateTagDisplayOrder.
func (mr *MockStoreMockRecorder) UpdateTagDisplayOrder(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTagDisplayOrder", reflect.TypeOf((*MockStore)(nil).UpdateTagDisplayOrder), ctx, arg)
}

// UpdateUserCredentials mocks base method.
func (m *MockStore) UpdateUserCredentials(ctx context.Context, arg db.UpdateUserCredentialsParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserCredentials", ctx, arg)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserCredentials indicates an expected call of UpdateUserCredentials.
func (mr *MockStoreMockRecorder) UpdateUserCredentials(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserCredentials", reflect.TypeOf((*MockStore)(nil).UpdateUserCredentials), ctx, arg)
}

// UpdateUserPassword mocks base method.
func (m *MockStore) UpdateUserPassword(ctx context.Context, passwordHash string) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserPassword", ctx, passwordHash)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserPassword indicates an expected call of UpdateUserPassword.
func (mr *MockStoreMockRecorder) UpdateUserPassword(ctx, passwordHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserPassword", reflect.TypeOf((*MockStore)(nil).UpdateUserPassword), ctx, passwordHash)
}

// UpdateUserUsername mocks base method.
func (m *MockStore) UpdateUserUsername(ctx context.Context, username string) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserUsername", ctx, username)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserUsername indicates an expected call of UpdateUserUsername.
func (mr *MockStoreMockRecorder) UpdateUserUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserUsername", reflect.TypeOf((*MockStore)(nil).UpdateUserUsername), ctx, username)
}

// UpdateView mocks base method.
func (m *MockStore) UpdateView(ctx context.Context, arg db.UpdateViewParams) (db.View, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateView", ctx, arg)
	ret0, _ := ret[0].(db.View)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateView indicates an expected call of UpdateView.
func (mr *MockStoreMockRecorder) UpdateView(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateView", reflect.TypeOf((*MockStore)(nil).UpdateView), ctx, arg)
}

// UpdateViewOrder mocks base method.
func (m *MockStore) UpdateViewOrder(ctx context.Context, arg db.UpdateViewOrderParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateViewOrder", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateViewOrder indicates an expected call of UpdateViewOrder.
func (mr *MockStoreMockRecorder) UpdateViewOrder(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateViewOrder", reflect.TypeOf((*MockStore)(nil).UpdateViewOrder), ctx, arg)
}

// UpsertNotification mocks base method.
func (m *MockStore) UpsertNotification(ctx context.Context, arg db.UpsertNotificationParams) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertNotification", ctx, arg)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertNotification indicates an expected call of UpsertNotification.
func (mr *MockStoreMockRecorder) UpsertNotification(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertNotification", reflect.TypeOf((*MockStore)(nil).UpsertNotification), ctx, arg)
}

// UpsertPullRequest mocks base method.
func (m *MockStore) UpsertPullRequest(ctx context.Context, arg db.UpsertPullRequestParams) (db.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertPullRequest", ctx, arg)
	ret0, _ := ret[0].(db.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertPullRequest indicates an expected call of UpsertPullRequest.
func (mr *MockStoreMockRecorder) UpsertPullRequest(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertPullRequest", reflect.TypeOf((*MockStore)(nil).UpsertPullRequest), ctx, arg)
}

// UpsertRepository mocks base method.
func (m *MockStore) UpsertRepository(ctx context.Context, arg db.UpsertRepositoryParams) (db.Repository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertRepository", ctx, arg)
	ret0, _ := ret[0].(db.Repository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertRepository indicates an expected call of UpsertRepository.
func (mr *MockStoreMockRecorder) UpsertRepository(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertRepository", reflect.TypeOf((*MockStore)(nil).UpsertRepository), ctx, arg)
}

// UpsertSyncState mocks base method.
func (m *MockStore) UpsertSyncState(ctx context.Context, arg db.UpsertSyncStateParams) (db.UpsertSyncStateRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertSyncState", ctx, arg)
	ret0, _ := ret[0].(db.UpsertSyncStateRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertSyncState indicates an expected call of UpsertSyncState.
func (mr *MockStoreMockRecorder) UpsertSyncState(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertSyncState", reflect.TypeOf((*MockStore)(nil).UpsertSyncState), ctx, arg)
}

// UpsertTag mocks base method.
func (m *MockStore) UpsertTag(ctx context.Context, arg db.UpsertTagParams) (db.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertTag", ctx, arg)
	ret0, _ := ret[0].(db.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertTag indicates an expected call of UpsertTag.
func (mr *MockStoreMockRecorder) UpsertTag(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertTag", reflect.TypeOf((*MockStore)(nil).UpsertTag), ctx, arg)
}
