// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type Notification struct {
	ID                      int64
	GithubID                string
	RepositoryID            int64
	PullRequestID           sql.NullInt64
	SubjectType             string
	SubjectTitle            string
	SubjectUrl              sql.NullString
	SubjectLatestCommentUrl sql.NullString
	Reason                  sql.NullString
	Archived                bool
	GithubUnread            sql.NullBool
	GithubUpdatedAt         sql.NullTime
	GithubLastReadAt        sql.NullTime
	GithubUrl               sql.NullString
	GithubSubscriptionUrl   sql.NullString
	ImportedAt              time.Time
	Payload                 pqtype.NullRawMessage
	SubjectRaw              pqtype.NullRawMessage
	SubjectFetchedAt        sql.NullTime
	AuthorLogin             sql.NullString
	AuthorID                sql.NullInt64
	IsRead                  bool
	Muted                   bool
	SnoozedUntil            sql.NullTime
	EffectiveSortDate       time.Time
	SnoozedAt               sql.NullTime
	Starred                 bool
	Filtered                bool
	TagIds                  []int64
	SubjectNumber           sql.NullInt32
	SubjectState            sql.NullString
	SubjectMerged           sql.NullBool
	SubjectStateReason      sql.NullString
}

type PullRequest struct {
	ID           int64
	RepositoryID int64
	GithubID     sql.NullInt64
	NodeID       sql.NullString
	Number       int32
	Title        sql.NullString
	State        sql.NullString
	Draft        sql.NullBool
	Merged       sql.NullBool
	AuthorLogin  sql.NullString
	AuthorID     sql.NullInt64
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	ClosedAt     sql.NullTime
	MergedAt     sql.NullTime
	Raw          pqtype.NullRawMessage
}

type Repository struct {
	ID             int64
	GithubID       sql.NullInt64
	NodeID         sql.NullString
	Name           string
	FullName       string
	OwnerLogin     sql.NullString
	OwnerID        sql.NullInt64
	Private        sql.NullBool
	Description    sql.NullString
	HtmlUrl        sql.NullString
	Fork           sql.NullBool
	Visibility     sql.NullString
	DefaultBranch  sql.NullString
	Archived       sql.NullBool
	Disabled       sql.NullBool
	PushedAt       sql.NullTime
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	Raw            pqtype.NullRawMessage
	OwnerAvatarUrl sql.NullString
	OwnerHtmlUrl   sql.NullString
}

type Rule struct {
	ID           int64
	Name         string
	Description  sql.NullString
	Query        sql.NullString
	Enabled      bool
	Actions      json.RawMessage
	DisplayOrder int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
	ViewID       sql.NullInt64
}

type SyncState struct {
	ID                   int32
	LastSuccessfulPoll   sql.NullTime
	LastNotificationEtag sql.NullString
	CreatedAt            time.Time
	UpdatedAt            time.Time
	LatestNotificationAt sql.NullTime
}

type Tag struct {
	ID           int64
	Name         string
	Color        sql.NullString
	Description  sql.NullString
	CreatedAt    time.Time
	DisplayOrder int32
	Slug         string
}

type TagAssignment struct {
	ID         int64
	TagID      int64
	EntityType string
	EntityID   int64
	CreatedAt  time.Time
}

type User struct {
	ID           int64
	Username     string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type View struct {
	ID           int64
	Name         string
	Description  sql.NullString
	IsDefault    bool
	CreatedAt    time.Time
	Icon         sql.NullString
	Slug         string
	Query        sql.NullString
	DisplayOrder int32
}
