// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pull_requests.sql

package db

import (
	"context"
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

const getPullRequestByID = `-- name: GetPullRequestByID :one
SELECT id, repository_id, github_id, node_id, number, title, state, draft, merged, author_login, author_id, created_at, updated_at, closed_at, merged_at, raw
FROM pull_requests
WHERE id = $1
`

func (q *Queries) GetPullRequestByID(ctx context.Context, id int64) (PullRequest, error) {
	row := q.db.QueryRowContext(ctx, getPullRequestByID, id)
	var i PullRequest
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.GithubID,
		&i.NodeID,
		&i.Number,
		&i.Title,
		&i.State,
		&i.Draft,
		&i.Merged,
		&i.AuthorLogin,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
		&i.MergedAt,
		&i.Raw,
	)
	return i, err
}

const getPullRequestByRepositoryAndNumber = `-- name: GetPullRequestByRepositoryAndNumber :one
SELECT id, repository_id, github_id, node_id, number, title, state, draft, merged, author_login, author_id, created_at, updated_at, closed_at, merged_at, raw
FROM pull_requests
WHERE repository_id = $1
  AND number = $2
`

type GetPullRequestByRepositoryAndNumberParams struct {
	RepositoryID int64
	Number       int32
}

func (q *Queries) GetPullRequestByRepositoryAndNumber(ctx context.Context, arg GetPullRequestByRepositoryAndNumberParams) (PullRequest, error) {
	row := q.db.QueryRowContext(ctx, getPullRequestByRepositoryAndNumber, arg.RepositoryID, arg.Number)
	var i PullRequest
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.GithubID,
		&i.NodeID,
		&i.Number,
		&i.Title,
		&i.State,
		&i.Draft,
		&i.Merged,
		&i.AuthorLogin,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
		&i.MergedAt,
		&i.Raw,
	)
	return i, err
}

const upsertPullRequest = `-- name: UpsertPullRequest :one
INSERT INTO pull_requests (
    repository_id,
    github_id,
    node_id,
    number,
    title,
    state,
    draft,
    merged,
    author_login,
    author_id,
    created_at,
    updated_at,
    closed_at,
    merged_at,
    raw
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15
)
ON CONFLICT (repository_id, number) DO UPDATE
SET github_id = COALESCE(EXCLUDED.github_id, pull_requests.github_id),
    node_id = COALESCE(EXCLUDED.node_id, pull_requests.node_id),
    title = COALESCE(EXCLUDED.title, pull_requests.title),
    state = COALESCE(EXCLUDED.state, pull_requests.state),
    draft = COALESCE(EXCLUDED.draft, pull_requests.draft),
    merged = COALESCE(EXCLUDED.merged, pull_requests.merged),
    author_login = COALESCE(EXCLUDED.author_login, pull_requests.author_login),
    author_id = COALESCE(EXCLUDED.author_id, pull_requests.author_id),
    created_at = COALESCE(EXCLUDED.created_at, pull_requests.created_at),
    updated_at = COALESCE(EXCLUDED.updated_at, pull_requests.updated_at),
    closed_at = COALESCE(EXCLUDED.closed_at, pull_requests.closed_at),
    merged_at = COALESCE(EXCLUDED.merged_at, pull_requests.merged_at),
    raw = COALESCE(EXCLUDED.raw, pull_requests.raw)
RETURNING id, repository_id, github_id, node_id, number, title, state, draft, merged, author_login, author_id, created_at, updated_at, closed_at, merged_at, raw
`

type UpsertPullRequestParams struct {
	RepositoryID int64
	GithubID     sql.NullInt64
	NodeID       sql.NullString
	Number       int32
	Title        sql.NullString
	State        sql.NullString
	Draft        sql.NullBool
	Merged       sql.NullBool
	AuthorLogin  sql.NullString
	AuthorID     sql.NullInt64
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	ClosedAt     sql.NullTime
	MergedAt     sql.NullTime
	Raw          pqtype.NullRawMessage
}

func (q *Queries) UpsertPullRequest(ctx context.Context, arg UpsertPullRequestParams) (PullRequest, error) {
	row := q.db.QueryRowContext(ctx, upsertPullRequest,
		arg.RepositoryID,
		arg.GithubID,
		arg.NodeID,
		arg.Number,
		arg.Title,
		arg.State,
		arg.Draft,
		arg.Merged,
		arg.AuthorLogin,
		arg.AuthorID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ClosedAt,
		arg.MergedAt,
		arg.Raw,
	)
	var i PullRequest
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.GithubID,
		&i.NodeID,
		&i.Number,
		&i.Title,
		&i.State,
		&i.Draft,
		&i.Merged,
		&i.AuthorLogin,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
		&i.MergedAt,
		&i.Raw,
	)
	return i, err
}
