// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repositories.sql

package db

import (
	"context"
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

const findRepositoryByFullName = `-- name: FindRepositoryByFullName :one
SELECT id, github_id, node_id, name, full_name, owner_login, owner_id, private, description, html_url, fork, visibility, default_branch, archived, disabled, pushed_at, created_at, updated_at, raw, owner_avatar_url, owner_html_url
FROM repositories
WHERE full_name = $1
`

func (q *Queries) FindRepositoryByFullName(ctx context.Context, fullName string) (Repository, error) {
	row := q.db.QueryRowContext(ctx, findRepositoryByFullName, fullName)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.NodeID,
		&i.Name,
		&i.FullName,
		&i.OwnerLogin,
		&i.OwnerID,
		&i.Private,
		&i.Description,
		&i.HtmlUrl,
		&i.Fork,
		&i.Visibility,
		&i.DefaultBranch,
		&i.Archived,
		&i.Disabled,
		&i.PushedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Raw,
		&i.OwnerAvatarUrl,
		&i.OwnerHtmlUrl,
	)
	return i, err
}

const getRepositoryByID = `-- name: GetRepositoryByID :one
SELECT id, github_id, node_id, name, full_name, owner_login, owner_id, private, description, html_url, fork, visibility, default_branch, archived, disabled, pushed_at, created_at, updated_at, raw, owner_avatar_url, owner_html_url
FROM repositories
WHERE id = $1
`

func (q *Queries) GetRepositoryByID(ctx context.Context, id int64) (Repository, error) {
	row := q.db.QueryRowContext(ctx, getRepositoryByID, id)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.NodeID,
		&i.Name,
		&i.FullName,
		&i.OwnerLogin,
		&i.OwnerID,
		&i.Private,
		&i.Description,
		&i.HtmlUrl,
		&i.Fork,
		&i.Visibility,
		&i.DefaultBranch,
		&i.Archived,
		&i.Disabled,
		&i.PushedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Raw,
		&i.OwnerAvatarUrl,
		&i.OwnerHtmlUrl,
	)
	return i, err
}

const listRepositories = `-- name: ListRepositories :many
SELECT id, github_id, node_id, name, full_name, owner_login, owner_id, private, description, html_url, fork, visibility, default_branch, archived, disabled, pushed_at, created_at, updated_at, raw, owner_avatar_url, owner_html_url
FROM repositories
ORDER BY full_name
`

func (q *Queries) ListRepositories(ctx context.Context) ([]Repository, error) {
	rows, err := q.db.QueryContext(ctx, listRepositories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repository
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.GithubID,
			&i.NodeID,
			&i.Name,
			&i.FullName,
			&i.OwnerLogin,
			&i.OwnerID,
			&i.Private,
			&i.Description,
			&i.HtmlUrl,
			&i.Fork,
			&i.Visibility,
			&i.DefaultBranch,
			&i.Archived,
			&i.Disabled,
			&i.PushedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Raw,
			&i.OwnerAvatarUrl,
			&i.OwnerHtmlUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRepository = `-- name: UpsertRepository :one
INSERT INTO repositories (
    github_id,
    node_id,
    name,
    full_name,
    owner_login,
    owner_id,
    private,
    description,
    html_url,
    owner_avatar_url,
    owner_html_url,
    fork,
    visibility,
    default_branch,
    archived,
    disabled,
    pushed_at,
    created_at,
    updated_at,
    raw
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    COALESCE($15, FALSE),
    $16,
    $17,
    $18,
    $19,
    $20
)
ON CONFLICT (full_name) DO UPDATE
SET github_id = EXCLUDED.github_id,
    node_id = EXCLUDED.node_id,
    name = EXCLUDED.name,
    owner_login = EXCLUDED.owner_login,
    owner_id = EXCLUDED.owner_id,
    private = EXCLUDED.private,
    description = EXCLUDED.description,
    html_url = EXCLUDED.html_url,
    owner_avatar_url = EXCLUDED.owner_avatar_url,
    owner_html_url = EXCLUDED.owner_html_url,
    fork = EXCLUDED.fork,
    visibility = EXCLUDED.visibility,
    default_branch = EXCLUDED.default_branch,
    archived = EXCLUDED.archived,
    disabled = EXCLUDED.disabled,
    pushed_at = EXCLUDED.pushed_at,
    created_at = COALESCE(EXCLUDED.created_at, repositories.created_at),
    updated_at = COALESCE(EXCLUDED.updated_at, repositories.updated_at),
    raw = EXCLUDED.raw
RETURNING id, github_id, node_id, name, full_name, owner_login, owner_id, private, description, html_url, fork, visibility, default_branch, archived, disabled, pushed_at, created_at, updated_at, raw, owner_avatar_url, owner_html_url
`

type UpsertRepositoryParams struct {
	GithubID       sql.NullInt64
	NodeID         sql.NullString
	Name           string
	FullName       string
	OwnerLogin     sql.NullString
	OwnerID        sql.NullInt64
	Private        sql.NullBool
	Description    sql.NullString
	HtmlUrl        sql.NullString
	OwnerAvatarUrl sql.NullString
	OwnerHtmlUrl   sql.NullString
	Fork           sql.NullBool
	Visibility     sql.NullString
	DefaultBranch  sql.NullString
	Archived       interface{}
	Disabled       sql.NullBool
	PushedAt       sql.NullTime
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	Raw            pqtype.NullRawMessage
}

func (q *Queries) UpsertRepository(ctx context.Context, arg UpsertRepositoryParams) (Repository, error) {
	row := q.db.QueryRowContext(ctx, upsertRepository,
		arg.GithubID,
		arg.NodeID,
		arg.Name,
		arg.FullName,
		arg.OwnerLogin,
		arg.OwnerID,
		arg.Private,
		arg.Description,
		arg.HtmlUrl,
		arg.OwnerAvatarUrl,
		arg.OwnerHtmlUrl,
		arg.Fork,
		arg.Visibility,
		arg.DefaultBranch,
		arg.Archived,
		arg.Disabled,
		arg.PushedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Raw,
	)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.NodeID,
		&i.Name,
		&i.FullName,
		&i.OwnerLogin,
		&i.OwnerID,
		&i.Private,
		&i.Description,
		&i.HtmlUrl,
		&i.Fork,
		&i.Visibility,
		&i.DefaultBranch,
		&i.Archived,
		&i.Disabled,
		&i.PushedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Raw,
		&i.OwnerAvatarUrl,
		&i.OwnerHtmlUrl,
	)
	return i, err
}
