// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rules.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/sqlc-dev/pqtype"
)

const createRule = `-- name: CreateRule :one
INSERT INTO rules (
    name,
    description,
    query,
    view_id,
    enabled,
    actions,
    display_order
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, name, description, query, enabled, actions, display_order, created_at, updated_at, view_id
`

type CreateRuleParams struct {
	Name         string
	Description  sql.NullString
	Query        sql.NullString
	ViewID       sql.NullInt64
	Enabled      bool
	Actions      json.RawMessage
	DisplayOrder int32
}

func (q *Queries) CreateRule(ctx context.Context, arg CreateRuleParams) (Rule, error) {
	row := q.db.QueryRowContext(ctx, createRule,
		arg.Name,
		arg.Description,
		arg.Query,
		arg.ViewID,
		arg.Enabled,
		arg.Actions,
		arg.DisplayOrder,
	)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Query,
		&i.Enabled,
		&i.Actions,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ViewID,
	)
	return i, err
}

const deleteRule = `-- name: DeleteRule :exec
DELETE FROM rules
WHERE id = $1
`

func (q *Queries) DeleteRule(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRule, id)
	return err
}

const getRule = `-- name: GetRule :one
SELECT id, name, description, query, enabled, actions, display_order, created_at, updated_at, view_id
FROM rules
WHERE id = $1
`

func (q *Queries) GetRule(ctx context.Context, id int64) (Rule, error) {
	row := q.db.QueryRowContext(ctx, getRule, id)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Query,
		&i.Enabled,
		&i.Actions,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ViewID,
	)
	return i, err
}

const getRulesByViewID = `-- name: GetRulesByViewID :many
SELECT id, name, description, query, enabled, actions, display_order, created_at, updated_at, view_id
FROM rules
WHERE view_id = $1
`

func (q *Queries) GetRulesByViewID(ctx context.Context, viewID sql.NullInt64) ([]Rule, error) {
	rows, err := q.db.QueryContext(ctx, getRulesByViewID, viewID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rule
	for rows.Next() {
		var i Rule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Query,
			&i.Enabled,
			&i.Actions,
			&i.DisplayOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ViewID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledRulesOrdered = `-- name: ListEnabledRulesOrdered :many
SELECT id, name, description, query, enabled, actions, display_order, created_at, updated_at, view_id
FROM rules
WHERE enabled = TRUE
ORDER BY display_order ASC, id ASC
`

func (q *Queries) ListEnabledRulesOrdered(ctx context.Context) ([]Rule, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledRulesOrdered)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rule
	for rows.Next() {
		var i Rule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Query,
			&i.Enabled,
			&i.Actions,
			&i.DisplayOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ViewID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRules = `-- name: ListRules :many
SELECT id, name, description, query, enabled, actions, display_order, created_at, updated_at, view_id
FROM rules
ORDER BY display_order ASC, id ASC
`

func (q *Queries) ListRules(ctx context.Context) ([]Rule, error) {
	rows, err := q.db.QueryContext(ctx, listRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rule
	for rows.Next() {
		var i Rule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Query,
			&i.Enabled,
			&i.Actions,
			&i.DisplayOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ViewID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRule = `-- name: UpdateRule :one
UPDATE rules
SET name = COALESCE($1, name),
    description = COALESCE($2, description),
    query = COALESCE($3, query),
    view_id = COALESCE($4, view_id),
    enabled = COALESCE($5, enabled),
    actions = COALESCE($6, actions),
    updated_at = NOW()
WHERE id = $7
RETURNING id, name, description, query, enabled, actions, display_order, created_at, updated_at, view_id
`

type UpdateRuleParams struct {
	Name        sql.NullString
	Description sql.NullString
	Query       sql.NullString
	ViewID      sql.NullInt64
	Enabled     sql.NullBool
	Actions     pqtype.NullRawMessage
	ID          int64
}

func (q *Queries) UpdateRule(ctx context.Context, arg UpdateRuleParams) (Rule, error) {
	row := q.db.QueryRowContext(ctx, updateRule,
		arg.Name,
		arg.Description,
		arg.Query,
		arg.ViewID,
		arg.Enabled,
		arg.Actions,
		arg.ID,
	)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Query,
		&i.Enabled,
		&i.Actions,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ViewID,
	)
	return i, err
}

const updateRuleOrder = `-- name: UpdateRuleOrder :exec
UPDATE rules
SET display_order = $1
WHERE id = $2
`

type UpdateRuleOrderParams struct {
	DisplayOrder int32
	ID           int64
}

func (q *Queries) UpdateRuleOrder(ctx context.Context, arg UpdateRuleOrderParams) error {
	_, err := q.db.ExecContext(ctx, updateRuleOrder, arg.DisplayOrder, arg.ID)
	return err
}
