// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sync_state.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const getSyncState = `-- name: GetSyncState :one
SELECT id,
       last_successful_poll,
       latest_notification_at,
       last_notification_etag,
       created_at,
       updated_at
FROM sync_state
WHERE id = 1
`

type GetSyncStateRow struct {
	ID                   int32
	LastSuccessfulPoll   sql.NullTime
	LatestNotificationAt sql.NullTime
	LastNotificationEtag sql.NullString
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

func (q *Queries) GetSyncState(ctx context.Context) (GetSyncStateRow, error) {
	row := q.db.QueryRowContext(ctx, getSyncState)
	var i GetSyncStateRow
	err := row.Scan(
		&i.ID,
		&i.LastSuccessfulPoll,
		&i.LatestNotificationAt,
		&i.LastNotificationEtag,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSyncState = `-- name: UpdateSyncState :one
UPDATE sync_state
SET last_successful_poll  = $1,
    latest_notification_at = $2,
    last_notification_etag = $3,
    updated_at = now()
WHERE id = 1
RETURNING id,
          last_successful_poll,
          latest_notification_at,
          last_notification_etag,
          created_at,
          updated_at
`

type UpdateSyncStateParams struct {
	LastSuccessfulPoll   sql.NullTime
	LatestNotificationAt sql.NullTime
	LastNotificationEtag sql.NullString
}

type UpdateSyncStateRow struct {
	ID                   int32
	LastSuccessfulPoll   sql.NullTime
	LatestNotificationAt sql.NullTime
	LastNotificationEtag sql.NullString
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

func (q *Queries) UpdateSyncState(ctx context.Context, arg UpdateSyncStateParams) (UpdateSyncStateRow, error) {
	row := q.db.QueryRowContext(ctx, updateSyncState, arg.LastSuccessfulPoll, arg.LatestNotificationAt, arg.LastNotificationEtag)
	var i UpdateSyncStateRow
	err := row.Scan(
		&i.ID,
		&i.LastSuccessfulPoll,
		&i.LatestNotificationAt,
		&i.LastNotificationEtag,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSyncState = `-- name: UpsertSyncState :one
INSERT INTO sync_state (id, last_successful_poll, latest_notification_at, last_notification_etag)
VALUES (1, $1, $2, $3)
ON CONFLICT (id) DO UPDATE
SET last_successful_poll  = EXCLUDED.last_successful_poll,
    latest_notification_at = EXCLUDED.latest_notification_at,
    last_notification_etag = EXCLUDED.last_notification_etag,
    updated_at = now()
RETURNING id,
          last_successful_poll,
          latest_notification_at,
          last_notification_etag,
          created_at,
          updated_at
`

type UpsertSyncStateParams struct {
	LastSuccessfulPoll   sql.NullTime
	LatestNotificationAt sql.NullTime
	LastNotificationEtag sql.NullString
}

type UpsertSyncStateRow struct {
	ID                   int32
	LastSuccessfulPoll   sql.NullTime
	LatestNotificationAt sql.NullTime
	LastNotificationEtag sql.NullString
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

func (q *Queries) UpsertSyncState(ctx context.Context, arg UpsertSyncStateParams) (UpsertSyncStateRow, error) {
	row := q.db.QueryRowContext(ctx, upsertSyncState, arg.LastSuccessfulPoll, arg.LatestNotificationAt, arg.LastNotificationEtag)
	var i UpsertSyncStateRow
	err := row.Scan(
		&i.ID,
		&i.LastSuccessfulPoll,
		&i.LatestNotificationAt,
		&i.LastNotificationEtag,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
