// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package db

import (
	"context"
	"database/sql"
)

const assignTagToEntity = `-- name: AssignTagToEntity :one
INSERT INTO tag_assignments (
    tag_id,
    entity_type,
    entity_id
)
VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT (tag_id, entity_type, entity_id) DO UPDATE
SET entity_type = EXCLUDED.entity_type
RETURNING id, tag_id, entity_type, entity_id, created_at
`

type AssignTagToEntityParams struct {
	TagID      int64
	EntityType string
	EntityID   int64
}

func (q *Queries) AssignTagToEntity(ctx context.Context, arg AssignTagToEntityParams) (TagAssignment, error) {
	row := q.db.QueryRowContext(ctx, assignTagToEntity, arg.TagID, arg.EntityType, arg.EntityID)
	var i TagAssignment
	err := row.Scan(
		&i.ID,
		&i.TagID,
		&i.EntityType,
		&i.EntityID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags
WHERE id = $1
`

func (q *Queries) DeleteTag(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTag, id)
	return err
}

const getTag = `-- name: GetTag :one
SELECT id, name, color, description, created_at, display_order, slug FROM tags
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetTag(ctx context.Context, id int64) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTag, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.Description,
		&i.CreatedAt,
		&i.DisplayOrder,
		&i.Slug,
	)
	return i, err
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, name, color, description, created_at, display_order, slug FROM tags
WHERE name = $1
LIMIT 1
`

func (q *Queries) GetTagByName(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagByName, name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.Description,
		&i.CreatedAt,
		&i.DisplayOrder,
		&i.Slug,
	)
	return i, err
}

const getTagBySlug = `-- name: GetTagBySlug :one
SELECT id, name, color, description, created_at, display_order, slug FROM tags
WHERE slug = $1
LIMIT 1
`

func (q *Queries) GetTagBySlug(ctx context.Context, slug string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagBySlug, slug)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.Description,
		&i.CreatedAt,
		&i.DisplayOrder,
		&i.Slug,
	)
	return i, err
}

const listAllTags = `-- name: ListAllTags :many
SELECT id, name, color, description, created_at, display_order, slug FROM tags
ORDER BY display_order, name
`

func (q *Queries) ListAllTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listAllTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.Description,
			&i.CreatedAt,
			&i.DisplayOrder,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForEntity = `-- name: ListTagsForEntity :many
SELECT t.id, t.name, t.color, t.description, t.created_at, t.display_order, t.slug
FROM tags t
JOIN tag_assignments ta ON ta.tag_id = t.id
WHERE ta.entity_type = $1
  AND ta.entity_id = $2
ORDER BY t.name
`

type ListTagsForEntityParams struct {
	EntityType string
	EntityID   int64
}

func (q *Queries) ListTagsForEntity(ctx context.Context, arg ListTagsForEntityParams) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTagsForEntity, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.Description,
			&i.CreatedAt,
			&i.DisplayOrder,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTagAssignment = `-- name: RemoveTagAssignment :exec
DELETE FROM tag_assignments
WHERE tag_id = $1
  AND entity_type = $2
  AND entity_id = $3
`

type RemoveTagAssignmentParams struct {
	TagID      int64
	EntityType string
	EntityID   int64
}

func (q *Queries) RemoveTagAssignment(ctx context.Context, arg RemoveTagAssignmentParams) error {
	_, err := q.db.ExecContext(ctx, removeTagAssignment, arg.TagID, arg.EntityType, arg.EntityID)
	return err
}

const updateNotificationTagIds = `-- name: UpdateNotificationTagIds :exec
UPDATE notifications
SET tag_ids = (
    SELECT COALESCE(array_agg(DISTINCT tag_id), '{}')
    FROM tag_assignments
    WHERE entity_type = 'notification' AND entity_id = $1
)
WHERE id = $1
`

func (q *Queries) UpdateNotificationTagIds(ctx context.Context, notificationID int64) error {
	_, err := q.db.ExecContext(ctx, updateNotificationTagIds, notificationID)
	return err
}

const updateTag = `-- name: UpdateTag :one
UPDATE tags
SET name = $1,
    slug = $2,
    color = $3,
    description = $4
WHERE id = $5
RETURNING id, name, color, description, created_at, display_order, slug
`

type UpdateTagParams struct {
	Name        string
	Slug        string
	Color       sql.NullString
	Description sql.NullString
	ID          int64
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, updateTag,
		arg.Name,
		arg.Slug,
		arg.Color,
		arg.Description,
		arg.ID,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.Description,
		&i.CreatedAt,
		&i.DisplayOrder,
		&i.Slug,
	)
	return i, err
}

const updateTagDisplayOrder = `-- name: UpdateTagDisplayOrder :exec
UPDATE tags
SET display_order = $1
WHERE id = $2
`

type UpdateTagDisplayOrderParams struct {
	DisplayOrder int32
	ID           int64
}

func (q *Queries) UpdateTagDisplayOrder(ctx context.Context, arg UpdateTagDisplayOrderParams) error {
	_, err := q.db.ExecContext(ctx, updateTagDisplayOrder, arg.DisplayOrder, arg.ID)
	return err
}

const upsertTag = `-- name: UpsertTag :one
INSERT INTO tags (
    name,
    slug,
    color,
    description
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (name) DO UPDATE
SET slug = EXCLUDED.slug,
    color = EXCLUDED.color,
    description = EXCLUDED.description
RETURNING id, name, color, description, created_at, display_order, slug
`

type UpsertTagParams struct {
	Name        string
	Slug        string
	Color       sql.NullString
	Description sql.NullString
}

func (q *Queries) UpsertTag(ctx context.Context, arg UpsertTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, upsertTag,
		arg.Name,
		arg.Slug,
		arg.Color,
		arg.Description,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.Description,
		&i.CreatedAt,
		&i.DisplayOrder,
		&i.Slug,
	)
	return i, err
}
