// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: views.sql

package db

import (
	"context"
	"database/sql"
)

const createView = `-- name: CreateView :one
INSERT INTO views (
    name,
    slug,
    description,
    icon,
    is_default,
    query
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    COALESCE($5, FALSE),
    $6
)
RETURNING id, name, description, is_default, created_at, icon, slug, query, display_order
`

type CreateViewParams struct {
	Name        string
	Slug        string
	Description sql.NullString
	Icon        sql.NullString
	IsDefault   interface{}
	Query       sql.NullString
}

func (q *Queries) CreateView(ctx context.Context, arg CreateViewParams) (View, error) {
	row := q.db.QueryRowContext(ctx, createView,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Icon,
		arg.IsDefault,
		arg.Query,
	)
	var i View
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsDefault,
		&i.CreatedAt,
		&i.Icon,
		&i.Slug,
		&i.Query,
		&i.DisplayOrder,
	)
	return i, err
}

const deleteView = `-- name: DeleteView :one
DELETE FROM views
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteView(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, deleteView, id)
	err := row.Scan(&id)
	return id, err
}

const getView = `-- name: GetView :one
SELECT id, name, description, is_default, created_at, icon, slug, query, display_order
FROM views
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetView(ctx context.Context, id int64) (View, error) {
	row := q.db.QueryRowContext(ctx, getView, id)
	var i View
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsDefault,
		&i.CreatedAt,
		&i.Icon,
		&i.Slug,
		&i.Query,
		&i.DisplayOrder,
	)
	return i, err
}

const getViewBySlug = `-- name: GetViewBySlug :one
SELECT id, name, description, is_default, created_at, icon, slug, query, display_order
FROM views
WHERE slug = $1
LIMIT 1
`

func (q *Queries) GetViewBySlug(ctx context.Context, slug string) (View, error) {
	row := q.db.QueryRowContext(ctx, getViewBySlug, slug)
	var i View
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsDefault,
		&i.CreatedAt,
		&i.Icon,
		&i.Slug,
		&i.Query,
		&i.DisplayOrder,
	)
	return i, err
}

const listViews = `-- name: ListViews :many
SELECT id, name, description, is_default, created_at, icon, slug, query, display_order
FROM views
ORDER BY 
    CASE 
        WHEN display_order = 0 THEN name 
        ELSE LPAD(display_order::text, 10, '0') 
    END,
    name
`

func (q *Queries) ListViews(ctx context.Context) ([]View, error) {
	rows, err := q.db.QueryContext(ctx, listViews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []View
	for rows.Next() {
		var i View
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsDefault,
			&i.CreatedAt,
			&i.Icon,
			&i.Slug,
			&i.Query,
			&i.DisplayOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateView = `-- name: UpdateView :one
UPDATE views
SET name = COALESCE($1, views.name),
    slug = COALESCE($2, views.slug),
    description = COALESCE($3, views.description),
    icon = COALESCE($4, views.icon),
    is_default = COALESCE($5, views.is_default),
    query = COALESCE($6, views.query)
WHERE id = $7
RETURNING id, name, description, is_default, created_at, icon, slug, query, display_order
`

type UpdateViewParams struct {
	Name        sql.NullString
	Slug        sql.NullString
	Description sql.NullString
	Icon        sql.NullString
	IsDefault   sql.NullBool
	Query       sql.NullString
	ID          int64
}

func (q *Queries) UpdateView(ctx context.Context, arg UpdateViewParams) (View, error) {
	row := q.db.QueryRowContext(ctx, updateView,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Icon,
		arg.IsDefault,
		arg.Query,
		arg.ID,
	)
	var i View
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsDefault,
		&i.CreatedAt,
		&i.Icon,
		&i.Slug,
		&i.Query,
		&i.DisplayOrder,
	)
	return i, err
}

const updateViewOrder = `-- name: UpdateViewOrder :exec
UPDATE views
SET display_order = $1
WHERE id = $2
`

type UpdateViewOrderParams struct {
	DisplayOrder int32
	ID           int64
}

func (q *Queries) UpdateViewOrder(ctx context.Context, arg UpdateViewOrderParams) error {
	_, err := q.db.ExecContext(ctx, updateViewOrder, arg.DisplayOrder, arg.ID)
	return err
}
