// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ajbeattie/octobud/backend/internal/github/interfaces (interfaces: SyncOperations)
//
// Generated by this command:
//
//	mockgen -destination=internal/github/mocks/mock_sync.go -package=mocks github.com/ajbeattie/octobud/backend/internal/github/interfaces SyncOperations
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	types "github.com/ajbeattie/octobud/backend/internal/github/types"
	gomock "go.uber.org/mock/gomock"
)

// MockSyncOperations is a mock of SyncOperations interface.
type MockSyncOperations struct {
	ctrl     *gomock.Controller
	recorder *MockSyncOperationsMockRecorder
	isgomock struct{}
}

// MockSyncOperationsMockRecorder is the mock recorder for MockSyncOperations.
type MockSyncOperationsMockRecorder struct {
	mock *MockSyncOperations
}

// NewMockSyncOperations creates a new mock instance.
func NewMockSyncOperations(ctrl *gomock.Controller) *MockSyncOperations {
	mock := &MockSyncOperations{ctrl: ctrl}
	mock.recorder = &MockSyncOperationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyncOperations) EXPECT() *MockSyncOperationsMockRecorder {
	return m.recorder
}

// FetchNotificationsToSync mocks base method.
func (m *MockSyncOperations) FetchNotificationsToSync(ctx context.Context) ([]types.NotificationThread, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchNotificationsToSync", ctx)
	ret0, _ := ret[0].([]types.NotificationThread)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchNotificationsToSync indicates an expected call of FetchNotificationsToSync.
func (mr *MockSyncOperationsMockRecorder) FetchNotificationsToSync(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchNotificationsToSync", reflect.TypeOf((*MockSyncOperations)(nil).FetchNotificationsToSync), ctx)
}

// ProcessNotification mocks base method.
func (m *MockSyncOperations) ProcessNotification(ctx context.Context, thread types.NotificationThread) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessNotification", ctx, thread)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessNotification indicates an expected call of ProcessNotification.
func (mr *MockSyncOperationsMockRecorder) ProcessNotification(ctx, thread any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessNotification", reflect.TypeOf((*MockSyncOperations)(nil).ProcessNotification), ctx, thread)
}

// UpdateSyncStateAfterProcessing mocks base method.
func (m *MockSyncOperations) UpdateSyncStateAfterProcessing(ctx context.Context, latestUpdate time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSyncStateAfterProcessing", ctx, latestUpdate)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSyncStateAfterProcessing indicates an expected call of UpdateSyncStateAfterProcessing.
func (mr *MockSyncOperationsMockRecorder) UpdateSyncStateAfterProcessing(ctx, latestUpdate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSyncStateAfterProcessing", reflect.TypeOf((*MockSyncOperations)(nil).UpdateSyncStateAfterProcessing), ctx, latestUpdate)
}
